GET http://localhost:3000/getProducts
Content-Type: application/json

###
GET http://localhost:3000/
Content-Type: application/json

###
GET http://localhost:3000/users
Content-Type: application/json

###
GET http://localhost:3000/cart
Content-Type: application/json

###
POST http://localhost:3000/addUser
Content-Type: application/json

{
   "email": "test0@gmail.com",
    "password": "12345",
    "full_name": "mahesh.m",
    "mobile": "9876543210"
}
###

###
POST http://localhost:3000/login
Content-Type: application/json

{
   "email": "test0@gmail.com",
    "password": "12345"
}
###

###
POST http://localhost:3000/addProductToCart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1haGVzaC5tIiwiZW1haWwiOiJ0ZXN0MEBnbWFpbC5jb20iLCJpYXQiOjE3MTEwMTQ3MTAsImV4cCI6MTcxMTE4NzUxMH0.qixbz_qJYGZSEJrjWEsjBxR1lEQ8tD4URL6z5xcvqqY

{
    "email": "test@gmail.com",
    "product_id":12,
    "quantity":1
}
###
POST http://localhost:3000/getProductsOnUserId
Content-Type: application/json

{
    "email" : "mahesh@gmail.com"
}
###


DELETE http://localhost:3000/deleteUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1haGVzaC5tIiwiZW1haWwiOiJ0ZXN0MEBnbWFpbC5jb20iLCJpYXQiOjE3MTEwMTYzOTgsImV4cCI6MTcxMTE4OTE5OH0.aSwaPf-e4Hj-k6fqlUsGjK-SWLOKMitoE-h060dyAfw

{
    "email": "test0@gmail.com",
    "password": "123"
   
}
###
PUT http://localhost:3000/updateUser 
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test1234",
    "full_name": "testing123",
    "mobile": "12345123455"
  }
###
DELETE http://localhost:3000/deleteProductFromCart/12&test@gmail.com
Content-Type: application/json

###
GET http://localhost:3000/createProductTable
Content-Type: application/json

###
GET http://localhost:3000/addCol
Content-Type: application/json

###
POST http://localhost:3000/addProductsIntoProductsTable
Content-Type: application/json

{
    
}
###